import { BadRequestException, Body, Controller, Headers, Post, Req, Res } from '@nestjs/common';
import type { Request, Response } from 'express';
import { IsOptional, IsString, MaxLength, MinLength } from 'class-validator';
import type { ChatStreamEvent } from '@diamond/shared';
import { Public } from '../auth/auth.decorators';
import { TenantService } from '../tenant/tenant.service';
import { ChatLimitError, ChatLimitsService } from './chat-limits.service';
import { ChatService } from './chat.service';

class SendMessageDto {
  @IsOptional()
  @IsString()
  conversation_id?: string;

  @IsString()
  @MinLength(1)
  @MaxLength(4000)
  text: string;

  @IsOptional()
  @IsString()
  channel?: string;
}

/**
 * The widget's endpoint. Authenticated with the tenant's public widget key, not
 * the dealer's ERP key — the ERP credential never leaves the server.
 *
 * Replies stream back as Server-Sent Events so text appears as it is generated
 * and product cards land the moment a lookup returns.
 */
@Controller('chat')
export class ChatController {
  constructor(
    private readonly chat: ChatService,
    private readonly tenants: TenantService,
    private readonly limits: ChatLimitsService,
  ) {}

  // The live customer widget. Authenticates by widget key, not by session.
  @Public()
  @Post('message')
  async sendMessage(
    @Headers('x-widget-key') widgetKey: string | undefined,
    @Headers('x-visitor-id') visitorId: string | undefined,
    @Headers('origin') origin: string | undefined,
    @Body() dto: SendMessageDto,
    @Req() req: Request,
    @Res() res: Response,
  ): Promise<void> {
    if (!widgetKey) throw new BadRequestException('Missing X-Widget-Key header');
    const tenant = await this.tenants.findByWidgetKey(widgetKey);

    const conversation = dto.conversation_id
      ? await this.chat.getConversation(tenant.id, dto.conversation_id)
      : await this.chat.startConversation(tenant, dto.channel ?? 'web', sanitiseVisitorId(visitorId));
    if (!conversation) throw new BadRequestException('Unknown conversation');

    // Checked before the stream opens so a refusal is an ordinary HTTP error the
    // widget can show, and — more to the point — before any tokens are spent.
    try {
      await this.limits.assertAllowed(tenant, conversation.id, req.ip ?? 'unknown', origin);
    } catch (error) {
      if (error instanceof ChatLimitError) {
        // In-band rather than a 429: the widget already renders `error` events,
        // whereas a non-200 would throw inside its EventSource handling.
        res.writeHead(200, { 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' });
        res.write(
          `data: ${JSON.stringify({ type: 'error', message: error.message } satisfies ChatStreamEvent)}\n\n`,
        );
        res.end();
        return;
      }
      throw error;
    }

    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no',
    });

    const send = (event: ChatStreamEvent) => res.write(`data: ${JSON.stringify(event)}\n\n`);
    send({ type: 'conversation', conversation_id: conversation.id });

    try {
      for await (const event of this.chat.streamTurn(tenant, conversation, dto.text)) {
        send(event);
      }
    } catch (error) {
      send({ type: 'error', message: (error as Error).message });
    } finally {
      res.end();
    }
  }
}

/**
 * The visitor id is generated by the widget and stored in the browser, so it
 * arrives entirely untrusted. Bounded and character-restricted before it is
 * written: it is only ever counted, never displayed, and an unbounded header
 * would otherwise be a free write into our database.
 */
function sanitiseVisitorId(value: string | undefined): string | undefined {
  if (!value) return undefined;
  const trimmed = value.trim().slice(0, 64);
  return /^[A-Za-z0-9_-]+$/.test(trimmed) ? trimmed : undefined;
}
